# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=254)),
                ('link', models.SlugField(unique=True)),
                ('type', models.IntegerField(choices=[(1, 'Lesson'), (2, 'Worksheet'), (3, 'Guide')], default=1)),
                ('level', models.IntegerField(choices=[(0, 'K'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=0)),
                ('subject', models.IntegerField(choices=[(1, 'Science'), (2, 'Math'), (3, 'Language'), (4, 'Reading'), (5, 'Filipino'), (6, 'Araling Panlipunan')], default=1)),
                ('thumbnail', models.ImageField(upload_to=b'')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
    ]
