# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='link',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b''),
        ),
    ]
